import { Log } from "./logger";

const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJhcmppdGFzYWh1LjIwMjBAZ21haWwuY29tIiwiZXhwIjoxNzU3MzIwOTE2LCJpYXQiOjE3NTczMjAwMTYsImlzcyI6IkFmZm9yZCBNZWRpY2FsIFRlY2hub2xvZ2llcyBQcml2YXRlIExpbWl0ZWQiLCJqdGkiOiIzODJkYmMxYi1kOTkxLTQ3NDQtYTM1MC05YzhjN2JlY2MyYTAiLCJsb2NhbGUiOiJlbi1JTiIsIm5hbWUiOiJhcmppdGEgc2FodSIsInN1YiI6ImE2NzNmNzcwLTRhNTctNDViYi05YWVmLTczNmQ1ZTk3MmU3NyJ9LCJlbWFpbCI6ImFyaml0YXNhaHUuMjAyMEBnbWFpbC5jb20iLCJuYW1lIjoiYXJqaXRhIHNhaHUiLCJyb2xsTm8iOiIyMjAxNjQwMTAwMDc5IiwiYWNjZXNzQ29kZSI6InNBV1R1UiIsImNsaWVudElEIjoiYTY3M2Y3NzAtNGE1Ny00NWJiLTlhZWYtNzM2ZDVlOTcyZTc3IiwiY2xpZW50U2VjcmV0IjoiVmpuWGJoVFh4Z0dDckhxZSJ9.EfQaOza0v37C0Z_PNbg9mM8ZkWDu72aRY0aFYVe2gsU"; // from auth API

// Test sending a log
Log("frontend", "info", "api", "Logger setup test successful", token);
